### ISSUE TITLE
Can't get the metadata

### ISSUE THREAD

**Issue by daniloprates** [j201/meta-marked#13]
Hey there,

I'm having an issue trying to get the metadata out of a md file. This is my code:

App.js
```js
// Dependencies
var text = require('./index.md');
var metaRemarkable = require('meta-remarkable');
var md = new metaRemarkable();
var res = md.render(text);
console.log('META', res.meta);
console.log('HTML', res.html);
```

index.md
```markdown
---
Title: My awesome markdown file
Author: Me
---
 
#My nice title
```

and this is what I get:
![screen shot 2016-07-05 at 14 41 54](https://cloud.githubusercontent.com/assets/1504716/16593975/6393390a-42be-11e6-8585-4f18d53a8478.png)

Also tried with `...`

Any clues? Thanks!

**Comment by daniloprates** [comment]
Also tried with `...`

**Comment by daniloprates** [comment]
closing, as it seems to be the wrong rep. (came from the npm page).

**Comment by j201** [comment]
That text works fine for me just using `metaMarked(fs.readFileSync(myFileName, "utf-8"))`. Looks like you're using a fork, so I'd suggest contacting the maintainer of that repo.
