### ISSUE TITLE
Update insecure dependencies

### ISSUE THREAD

**Issue by PatrickHeneise** [j201/meta-marked#8]
Hi,

any chance to get the dependencies updated? Says 'insecure' by the dependency check.

Thanks!

**Comment by j201** [comment]
That's because of this issue, which hasn't been resolved yet: https://github.com/chjj/marked/issues/497

**Comment by PatrickHeneise** [comment]
Oh, ok. Thanks!

**Comment by boutell** [comment]
Looks like that issue has actually been resolved?

**Comment by j201** [comment]
Thanks, updated: d5c2a6f26790c6e95b45bb87b7078f8b3fd4bb5e
